graph TD
    %% Use a circular or force-directed renderer
    Node0((Node 0)) --- Node1((Node 1))
    Node0((Node 0)) --- Node5((Node 5))
    Node0((Node 0)) --- Node13((Node 13))
    Node1((Node 1)) --- Node2((Node 2))
    Node2((Node 2)) --- Node3((Node 3))
    Node3((Node 3)) --- Node4((Node 4))
    Node3((Node 3)) --- Node8((Node 8))
    Node4((Node 4)) --- Node5((Node 5))
    Node5((Node 5)) --- Node6((Node 6))
    Node6((Node 6)) --- Node7((Node 7))
    Node6((Node 6)) --- Node11((Node 11))
    Node7((Node 7)) --- Node8((Node 8))
    Node7((Node 7)) --- Node20((Node 20))
    Node8((Node 8)) --- Node9((Node 9))
    Node9((Node 9)) --- Node10((Node 10))
    Node9((Node 9)) --- Node14((Node 14))
    Node10((Node 10)) --- Node11((Node 11))
    Node11((Node 11)) --- Node12((Node 12))
    Node12((Node 12)) --- Node13((Node 13))
    Node12((Node 12)) --- Node17((Node 17))
    Node13((Node 13)) --- Node14((Node 14))
    Node14((Node 14)) --- Node15((Node 15))
    Node14((Node 14)) --- Node27((Node 27))
    Node15((Node 15)) --- Node16((Node 16))
    Node15((Node 15)) --- Node20((Node 20))
    Node16((Node 16)) --- Node17((Node 17))
    Node17((Node 17)) --- Node18((Node 18))
    Node18((Node 18)) --- Node19((Node 19))
    Node18((Node 18)) --- Node23((Node 23))
    Node19((Node 19)) --- Node20((Node 20))
    Node20((Node 20)) --- Node21((Node 21))
    Node21((Node 21)) --- Node22((Node 22))
    Node21((Node 21)) --- Node26((Node 26))
    Node21((Node 21)) --- Node34((Node 34))
    Node22((Node 22)) --- Node23((Node 23))
    Node23((Node 23)) --- Node24((Node 24))
    Node24((Node 24)) --- Node25((Node 25))
    Node24((Node 24)) --- Node29((Node 29))
    Node25((Node 25)) --- Node26((Node 26))
    Node26((Node 26)) --- Node27((Node 27))
    Node27((Node 27)) --- Node28((Node 28))
    Node27((Node 27)) --- Node32((Node 32))
    Node28((Node 28)) --- Node29((Node 29))
    Node29((Node 29)) --- Node30((Node 30))
    Node30((Node 30)) --- Node31((Node 31))
    Node30((Node 30)) --- Node35((Node 35))
    Node31((Node 31)) --- Node32((Node 32))
    Node32((Node 32)) --- Node33((Node 33))
    Node33((Node 33)) --- Node34((Node 34))
    Node33((Node 33)) --- Node38((Node 38))
    Node34((Node 34)) --- Node35((Node 35))
    Node35((Node 35)) --- Node36((Node 36))
    Node36((Node 36)) --- Node37((Node 37))
    Node37((Node 37)) --- Node38((Node 38))
    Node38((Node 38)) --- Node39((Node 39))